name: ðŸš€ Build, test, and release

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: âš™ï¸ Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.3'

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: iconv, intl, soap, mbstring, mysql, mysqli, gd
        ini-values: phar.readonly=0
        tools: composer

    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-cache-

    - uses: actions/checkout@v2

    - name: Install php-scoper
      run: |
        composer global config minimum-stability dev
        composer global require humbug/php-scoper --prefer-dist --no-interaction --no-progress

    - name: Install composer dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Run php-scoper
      run: php-scoper add-prefix

    - name: Remove composer dev dependencies
      run: composer update --no-dev --optimize-autoloader --prefer-dist --no-interaction --no-progress

    - name: Run npm install
      run: |
        npm install

    - name: Run npm build
      run: |
        npm run build

    - name: Trim to production node_modules
      run: |
        rm -rf node_modules
        npm install --production --no-bin-links

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/**/*

    - name: Upload languages
      uses: actions/upload-artifact@v2
      with:
        name: languages
        path: languages/**/*

    - name: Upload styles
      uses: actions/upload-artifact@v2
      with:
        name: css
        path: css/**/*

  test:
    name: ðŸ§ª Test
    needs: build
    strategy:
      matrix:
        multisite: ['0', '1']
        php:
        - '7.0'
        - '7.1'
        - '7.2'
        - '7.3'
        - '7.4'
        # - '8.0'
        wordpress:
        - '5.0'
        - '5.1'
        - '5.2'
        - '5.3'
        - '5.4'
        - '5.5'
        - '5.6'
        - latest
        - trunk
        exclude:
        - wordpress: '5.0'
          php: '7.4'
          multisite: '0'
        - wordpress: '5.1'
          php: '7.4'
          multisite: '0'
        - wordpress: '5.2'
          php: '7.4'
          multisite: '0'
        - wordpress: '5.0'
          php: '7.4'
          multisite: '1'
        - wordpress: '5.1'
          php: '7.4'
          multisite: '1'
        - wordpress: '5.2'
          php: '7.4'
          multisite: '1'
        # - wordpress: '5.0'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.1'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.2'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.3'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.4'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.5'
        #   php: '8.0'
        #   multisite: '0'
        # - wordpress: '5.0'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.1'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.2'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.3'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.4'
        #   php: '8.0'
        #   multisite: '1'
        # - wordpress: '5.5'
        #   php: '8.0'
        #   multisite: '1'
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - '3306:3306'
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: iconv, intl, xml, soap, opcache, pdo, pdo_mysql, mysqli, mbstring, gd
        ini-values: phar.readonly=0
        tools: phpunit:v7

    - uses: actions/checkout@v2

    - name: Download build files
      uses: actions/download-artifact@v2

    - name: Install WordPress Test Suite
      run: ./bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wordpress }}

    - name: Run phpunit
      run: |
        if [ ${{ matrix.multisite }} -eq 1 ]; then
          phpunit -c phpunit-multisite.xml $GITHUB_WORKSPACE        
        else
          phpunit $GITHUB_WORKSPACE
        fi

  coverage:
    name: ðŸ™ˆ Coverage
    needs:
    - build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306/tcp
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: iconv, intl, soap, mbstring, mysql, mysqli, gd
        ini-values: phar.readonly=0
        tools: phpunit:6.5.5

    - uses: actions/checkout@v2

    - name: Download build files
      uses: actions/download-artifact@v2

    - name: Install WordPress Test Suite
      run: ./bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports[3306] }} latest

    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_REPORTER_ID}}
      with:
        coverageCommand: phpunit --verbose -c phpunit.xml.dist --coverage-clover clover.xml
        coverageLocations: ${{github.workspace}}/clover.xml:clover

  deploy_to_worg:
    name: ðŸš€ RELEASE to WordPress.org
    runs-on: ubuntu-latest
    if: github.repository_owner == 'a-z-listing' && startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    - test
    steps:
    - uses: actions/checkout@v2

    - name: Download build files
      uses: actions/download-artifact@v2

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@1.5.0
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: a-z-listing
